config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  
  resources :parts do
    member do
      post :fitment
    end
  end

  resources :vehicles
  resources :discoveries do
    member do
      put "upvote" => "discoveries#upvote"
      put "downvote" => "discoveries#downvote"
    end
  end

  resources :users, only: [:show]

  get 'search' => 'search#index', as: :search
  get 'about' => 'pages#about'
  get 'blog' => 'pages#blog'
  get 'contact' => 'pages#contact'
  get 'help' => 'pages#help'

  root 'pages#home'

  

end

app/models/part.rb
class Part < ActiveRecord::Base
	has_many :oemfitments
	has_many :vehicles, through: :oemfitments
  belongs_to :user
  has_many :discoveries
  accepts_nested_attributes_for :vehicles, :reject_if => :all_blank, :allow_destroy => true
  validates :user_id, :manufacturer, :name, presence: true
	before_save :strip_fields
	before_validation :strip_fields


  private

  def strip_fields
  	self.name = name.strip.split.map(&:capitalize).join(' ')
    # self.description = description.strip.capitalize
    # self.part_number = part_number.strip
  	self.manufacturer = manufacturer.upcase.strip
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController

	before_action :set_part, only: [:show, :edit, :destroy, :fitment]
  	before_action :authenticate_user!, except: [:index, :show]

  def index
  	@parts = Part.all
  end

  def show
  end

  def new
  	@part = current_user.parts.build
  end

  def create
  	@part = current_user.parts.build(part_params)

  	if @part.save
  		redirect_to @part, notice: "New compatible part has been saved, thanks for being a ninja!"
  	else
  		render 'new'
  	end
  end

  def edit
  end

  def update
  	if @part.update(part_params)
  		redirect_to @part, notice: "Succesfully updated this part"
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@part.destroy
  	redirect_to parts_path
  end

  def fitment
    @make = params[:vehicle][:make].upcase
    @model = params[:vehicle][:model].upcase
    @year = params[:vehicle][:year]
    @vehicle = Vehicle.where(make: @make, model: @model, year: @year).first_or_create
    @oemfitment = current_user.oemfitments.build(part: @part, vehicle: @vehicle)

    if @oemfitment.save
      redirect_to @part, notice: "New oem model has been saved"
    else
      render 'show'
      # redirect_to @part, alert: "Didn't save for some reason" #Temporary fix 
    end
  end

  private

  def set_part
  	@part = Part.find(params[:id])
  end

  def part_params
  	params.require(:part).permit(:manufacturer, :description, :part_number, :comment, :name, steps_attributes: [:id, :content, :_destroy])
  end


end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/parts/_form.html.erb
<%= simple_form_for @part do |f| %>
	<% if @part.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@part.errors.count, "error") %> prevented this part from saving: </h2>
			<ul>
				<% @part.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
					<% end %>
			</ul>
		</div>
	<% end %>
<% end %>

<div class="ninja-panel pad-20">	
	<%= simple_form_for @part do |f| %>
		<h2 class="text-center">Describe the original part <a tabindex="0" class="btn btn-lg info-popup" role="button" data-toggle="popover" data-trigger="focus" title="What is being replaced?" data-content="Who originally made the part? What part is it? What model vehicle did it belong to?"><span class="badge"><i class="fa fa-question"></span></i></a></h2>
		<div class="row">
			<div class="col-lg-6"><div class="form-header">Manufacturer</div><%= f.input :manufacturer, required: false, label: false, placeholder: 'Manufacturer', input_html: { class: 'form-control input-lg dark-input'  } %></div>
			<div class="col-md-6"><div class="form-header">Part Name</div><%= f.input :name, required: false, label: false, placeholder: 'Description', input_html: { class: 'form-control input-lg dark-input'  } %></div>
		</div>
		<div class="row">
			<div class="col-lg-8"><div class="form-header">Description</div><%= f.input :description, as: :text, required: false, label: false, placeholder: 'Description', input_html: { class: 'form-control input-lg dark-input'  } %></div>
			<div class="col-lg-4"><div class="form-header">Part #</div><%= f.input :part_number, required: false, label: false, placeholder: 'Part #', input_html: { class: 'form-control input-lg dark-input'  } %></div>
		</div>
</div>
<div class="col-md-4 col-md-offset-4">
		<div class="ninja-panel mrg-top-20 pad-20 text-center">
                  <%= f.button :submit, "Create Compatibility" %>
	<% end %>
		</div>
</div>

app/views/parts/_part.html.erb
<tr data-link="<%= part_path(part) %>">
	<td><%= part.id %></td>
	<td><%= link_to part.user.username, part.user %></td>
	<td><%= part.manufacturer %></td>
	<td><%= part.name %></td>
	<td><%= part.part_number %></td>
	<td><%= link_to 'View', part, class: "btn btn-default" %></td>
	<td><%= link_to 'Delete', part, method: :delete, data: {confirm: "Are you sure"}, class: "btn btn-warning" %></td>
</tr>

app/views/parts/edit.html.erb
<h1>Parts#edit</h1>
<p>Find me in app/views/parts/edit.html.erb</p>

app/views/parts/index.html.erb
<div class="content">
	<div class="col-md-12">
		<h1 class="white-page-heading">Viewing all parts in the </h1>
		<h1 class="red-page-heading">Parts Ninja Database</h1>
		<div class="header-border"></div>
	</div>
	<div class="col-md-8 col-md-offset-2">	
		<table class="table table-hover">
    		<thead>
    			<tr>
			        <th>Part Id</th>
			        <th>Submitted By</th>
			        <th>Part Name</th>
			        <th>Modifications Required</th>
			        <th>View</th>
              <th>Delete</th>
		      	</tr>
    		</thead>
    		<tbody>
    			<%= render @parts %>
			</tbody>
  		</table>
	</div>
</div>

app/views/parts/new.html.erb
<div class="content">
	<div class="col-md-12">
		<h1 class="white-page-heading">Add a New Compatible Part</h1>
		<h1 class="red-page-heading">What did you discover?</h1>
		<div class="header-border"></div>
	</div>
	<div class="col-md-10 col-md-offset-1">	
		<%= render 'form' %>
	</div>
</div>

	

app/views/parts/show.html.erb
<div class="content">
	<div class="col-md-12">
		<h1 class="white-page-heading">Viewing Compatible Part</h1>
		<h1 class="red-page-heading"><%= @part.manufacturer %> <%= @part.name %></h1>
		<div class="header-border"></div>
	</div>
	<div class="col-md-10 col-md-offset-1">	
		<div class="ninja-panel pad-20">	
			<div class="row">
				<div class="col-md-4"><div class="form-header">Manufacturer:</div> <%= @part.manufacturer %> <br><div class="form-header">Part Name:</div> <%= @part.name %> <br><div class="form-header">Part Number:</div> <%= @part.part_number %></div>
				<div class="col-md-8"><div class="form-header">Description: </div> <%= @part.description %></div>
			</div>
			<br>
			<% unless @part.vehicles.count == 0 %>
				<div class="row mrg-top-20">
					<div class="col-md-12">		
						<h4 class="text-center mrg-btm-10">This part was designed for the following models:</h4>
						<div class="well dark-well">
							<div class="row">								
							</div>
							<% @part.oemfitments.each do |oemfitment| %>
								<%= link_to oemfitment.vehicle do %>
									<div class="">	
										<%= oemfitment.vehicle.year %> <%= oemfitment.vehicle.make %> <%=oemfitment.vehicle.model %>
								<% end %>
										<%= link_to oemfitment.user.username, oemfitment.user, class: "floatright" %>
									</div>
							<% end %>
						</div>
					</div>
				</div>
			<% end %>
			<h6 class="mrg-btm-10">Was this part designed for another vehicle or model?</h6>
			<%= form_tag fitment_part_path do %>
				<div class="col-md-3"><%= number_field(:vehicle, :year, class: 'input-lg dark-input fit', placeholder: ' Year') %></div>
				<div class="col-md-4"><%= text_field(:vehicle, :make, class: 'input-lg dark-input fit', placeholder: ' Make') %></div>
				<div class="col-md-3"><%= text_field(:vehicle, :model, class: 'input-lg dark-input fit', placeholder: ' Model') %></div>
				<div class="cold-md-1"><%= submit_tag "Add Vehicle", class: 'form-button btn btn-default'  %></div>	
			<% end %>
		</div>
		<% unless @part.discoveries.count == 0 %>
			<div class="ninja-panel pad-20 mrg-top-20">
				<h4 class="text-center mrg-btm-10">This part is also compatible with the following models:</h4>
					<% @part.discoveries.each do |discovery| %>
						<%= link_to discovery do %>
							<div class="col-md-6">
								<div class="well dark-well text-center">
										<%= discovery.compatible.year %> <%= discovery.compatible.make %> <%=discovery.compatible.model %>
								</div>		
							</div>
						<% end %>
					<% end %>
			</div>
		<% end %>
	</div>
</div>

	