config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  
  resources :parts do
    member do
      post :fitment
    end
  end

  resources :vehicles
  resources :discoveries do
    member do
      put "upvote" => "discoveries#upvote"
      put "downvote" => "discoveries#downvote"
    end
  end

  resources :users, only: [:show]

  get 'search' => 'search#index', as: :search
  get 'about' => 'pages#about'
  get 'blog' => 'pages#blog'
  get 'contact' => 'pages#contact'
  get 'help' => 'pages#help'

  root 'pages#home'

  

end

app/models/discovery.rb
class Discovery < ActiveRecord::Base
	belongs_to :user
	belongs_to :part
	belongs_to :oem, class_name: "Vehicle"
	belongs_to :compatible, class_name: "Vehicle"
	has_many :steps
	accepts_nested_attributes_for :steps, :reject_if => :all_blank, :allow_destroy => true
	validates :user_id, :part_id, :oem_id, :compatible_id, :replaces, presence: true
	acts_as_votable

	def score
		self.get_upvotes.size - self.get_downvotes.size
	end
end

app/controllers/discoveries_controller.rb
class DiscoveriesController < ApplicationController
	before_action :set_discovery, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@discoveries = Discovery.all
	end

	def show
		@steps = @discovery.steps
	end

	def new
		@discovery = current_user.discoveries.build	
	end

	def edit
	end

	def create
		#find OEM Vehicle
		@oem_make = params[:oem_vehicle][:make].upcase
  	@oem_model = params[:oem_vehicle][:model].upcase
  	@oem_year = params[:oem_vehicle][:year]
  	@oem_vehicle = Vehicle.where(:make => @oem_make, :model => @oem_model, :year => @oem_year).first_or_create

  	#find Compatible Vehicle
  	@compatible_make = params[:compatible_vehicle][:make].upcase
  	@compatible_model = params[:compatible_vehicle][:model].upcase
  	@compatible_year = params[:compatible_vehicle][:year]
  	@compatible_vehicle = Vehicle.where(:make => @compatible_make, :model => @compatible_model, :year => @compatible_year).first_or_create

  	#find part
  	@part_manufacturer = params[:part][:manufacturer].upcase.strip
  	@part_name = params[:part][:name].strip.split.map(&:capitalize).join(' ')
    @part = @oem_vehicle.parts.where(manufacturer: @part_manufacturer, name: @part_name).first 
    #@part = Part.where(manufacturer: @part_manufacturer, name: @part_name).first
    
    #Create Part if it doesn't exist
    unless @part
    	@part = current_user.parts.create(manufacturer: @part_manufacturer, name: @part_name)
    	@oemfitment = current_user.oemfitments.create(part: @part, vehicle: @oem_vehicle)
    end

    #Creates the Discovery with the above found records
		@discovery = current_user.discoveries.build(discovery_params)
		@discovery.oem = @oem_vehicle
		@discovery.compatible = @compatible_vehicle
		@discovery.part = @part

  	if @discovery.save
  		redirect_to @discovery, notice: "New discovery has been saved, thanks for being a ninja!"
  	else
  		render 'new'
  	end
	end

	def update
  	if @discovery.update(edit_discovery_params)
  		redirect_to @discovery, notice: "Succesfully updated this discovery"
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@discovery.destroy
  	redirect_to discoveries_path
  end

  def upvote
  	@discovery.upvote_from current_user
  	redirect_to @discovery
  end

  def downvote
  	@discovery.downvote_from current_user
  	redirect_to @discovery
  end

	private 

		def set_discovery
	  	@discovery = Discovery.find(params[:id])
	  end

		def discovery_params
			params.require(:discovery).permit(:replaces, :comments, :modifications, steps_attributes: [:id, :content, :_destroy])
		# 	params.require(:discovery).permit(:comment, :modifications, steps_attributes: [:id, :content, :_destroy])
		end
	
		def edit_discovery_params
			params.require(:discovery).permit(:comment, :replaces, :modifications)
		end
end

app/helpers/discoveries_helper.rb
module DiscoveriesHelper
end

app/views/discoveries/_discovery.html.erb
<!-- <tr>
	<td><%= discovery.id %></td>
	<td><%= link_to discovery.user.username, discovery.user %></td>
	<td><%= discovery.oem.year %> <%= discovery.oem.make %> <%= discovery.oem.model %></td>
	<td><%= discovery.compatible.year %> <%= discovery.compatible.make %> <%= discovery.compatible.model %></td>
	<td><%= discovery.replaces %></td>
	<td><%= link_to 'View', discovery, class: "btn btn-default" %></td>
	<td><%= link_to 'Delete', discovery, method: :delete, data: {confirm: "Are you sure"}, class: "btn btn-warning" %></td>
</tr>
 -->

	<div class="panel panel-default ninja-panel">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse-<%= discovery.id %>"><%= discovery.oem.year %> <%= discovery.oem.make %> <%= discovery.oem.model %> <i class="fa fa-arrow-left arrow-color"></i> <i><%= discovery.replaces %> </i><i class="fa fa-arrow-right arrow-color"></i> <%= discovery.compatible.year %> <%= discovery.compatible.make %> <%= discovery.compatible.model %> <span class="pull-right"><%= discovery.score %></span> </a>
            </h4>
        </div>
        <div id="collapse-<%= discovery.id %>" class="panel-collapse collapse">
            <div class="panel-body">
                <h5 class="pull-left text-uppercase mrg-auto-10">Discovered by: <%= link_to discovery.user.username, discovery.user %></h5>	 <div class="pull-right"><%= link_to 'View', discovery, class: "btn btn-default" %> <%= link_to 'Delete', discovery, method: :delete, data: {confirm: "Are you sure"}, class: "btn btn-danger" %></div>
            </div>
        </div>
    </div>

app/views/discoveries/_edit_form.html.erb
<%= simple_form_for @discovery do |f| %>
<div class="ninja-panel pad-20">	
		<h2 class="text-center">Describe the discovery <a tabindex="0" class="btn btn-lg info-popup" role="button" data-toggle="popover" data-trigger="focus" title="What is being replaced?" data-content="Who originally made the discovery? What discovery is it? What model vehicle did it belong to?"><span class="badge"><i class="fa fa-question"></span></i></a></h2>
		<% if @discovery.errors.any? %>
			<div id="errors">
				<h2><%= pluralize(@discovery.errors.count, "error") %> prevented this discovery from saving: </h2>
				<ul>
					<% @discovery.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
						<% end %>
				</ul>
			</div>
		<% end %>
		<div class="row">	
			<div class="form-inputs">
				<div class="col-lg-12"><div class="form-header">Comment</div><%= f.input :comment, required: false, label: false, placeholder: 'Do you have any noteworthy comments to add?', input_html: { class: 'form-control input-lg dark-input'  } %><div class="form-header">Replaces</div><%= f.input :replaces, required: false, label: false, placeholder: 'What parts are compatible? i.e. Wheel Bearings, chain guide, clutch plates', input_html: { class: 'form-control input-lg dark-input'  } %><div class="form-header">Are modifications required?</div><%= f.input :modifications, label: false, as: :boolean %>
			</div>
			</div>
		</div>
</div>
<div class="ninja-panel pad-20 mrg-top-20">
	<h3>Steps </h3>
		<div id="steps">
			<%= f.simple_fields_for(:steps) do |step| %>
				<%= render 'step_fields', :f => step %>
			<% end %>
				<div class="links">
					<%= link_to_add_association 'Add Step', f, :steps %>
				</div>
		</div>
</div>
<div class="col-md-4 col-md-offset-4">
	<div class="ninja-panel mrg-top-20 pad-20 text-center">
    <%= f.button :submit, "Update Discovery" %>
	</div>
</div>
<% end %>

app/views/discoveries/_form.html.erb
<%= simple_form_for @discovery do |f| %>
<div class="ninja-panel pad-20">	
		<h2 class="text-center">Describe the discovery <a tabindex="0" class="btn btn-lg info-popup" role="button" data-toggle="popover" data-trigger="focus" title="What is being replaced?" data-content="Who originally made the discovery? What discovery is it? What model vehicle did it belong to?"><span class="badge"><i class="fa fa-question"></span></i></a></h2>
		<% if @discovery.errors.any? %>
			<div id="errors">
				<h2><%= pluralize(@discovery.errors.count, "error") %> prevented this discovery from saving: </h2>
				<ul>
					<% @discovery.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
						<% end %>
				</ul>
			</div>
		<% end %>
		<div class="row">	
			<div class="form-inputs">
				<div class="col-md-6"><p>Part</p>
					<%= text_field(:part, :manufacturer, class: 'input-sm dark-input', placeholder: ' Manufacturer') %>
					<%= text_field(:part, :name, class: 'input-sm dark-input', placeholder: ' Name') %>
    				<div class="form-header">Are modifications required?</div> <div class="floatright"><%= f.check_box :modifications, label: false, as: :boolean, :data => { :size=>'small', 'on-text'=>'Yes', 'off-text'=>'No' } %></div>
    				</div>
				<div class="col-md-6"><p>Oem Vehicle</p>
					<%= number_field(:oem_vehicle, :year, class: 'input-sm dark-input', placeholder: ' Year') %>
					<%= text_field(:oem_vehicle, :make, class: 'input-sm dark-input', placeholder: ' Make') %>
					<%= text_field(:oem_vehicle, :model, class: 'input-sm dark-input', placeholder: ' Model') %>
				</div>
				<div class="col-md-6"><p>Compatible Vehicle</p>
					<%= number_field(:compatible_vehicle, :year, class: 'input-sm dark-input', placeholder: ' Year') %>
					<%= text_field(:compatible_vehicle, :make, class: 'input-sm dark-input', placeholder: ' Make') %>
					<%= text_field(:compatible_vehicle, :model, class: 'input-sm dark-input', placeholder: ' Model') %>
				</div>
				<div class="col-lg-12"><div class="form-header">Comment</div><%= f.input :comment, required: false, label: false, placeholder: 'Do you have any noteworthy comments to add?', input_html: { class: 'form-control input-lg dark-input'  } %><div class="form-header">Replaces</div><%= f.input :replaces, required: false, label: false, placeholder: 'What parts are compatible? i.e. Wheel Bearings, chain guide, clutch plates', input_html: { class: 'form-control input-lg dark-input'  } %></div>
			</div>
		</div>
</div>
<div class="ninja-panel pad-20 mrg-top-20">
	<h3>Steps </h3>
		<div id="steps">
			<%= f.simple_fields_for(:steps) do |step| %>
				<%= render 'step_fields', :f => step %>
			<% end %>
				<div class="links">
					<%= link_to_add_association 'Add Step', f, :steps %>
				</div>
		</div>
</div>
<div class="col-md-4 col-md-offset-4">
	<div class="ninja-panel mrg-top-20 pad-20 text-center">
    <%= f.button :submit, "Create Discovery" %>
	</div>
</div>
<% end %>

app/views/discoveries/_step_fields.html.erb
<div class="nested-fields">
	<%= f.input :content, placeholder: 'Please walk us through this step', input_html: { class: 'form-control input-lg dark-input'  } %>
	<%= link_to_remove_association "Remove Step", f %>
</div>

app/views/discoveries/edit.html.erb
<div class="content">
	<div class="col-md-12">
		<h1 class="white-page-heading">Edit your Discovery</h1>
		<h1 class="red-page-heading">Do it NAO</h1>
		<div class="header-border"></div>
	</div>
	<div class="col-md-10 col-md-offset-1">	
		<%= render 'edit_form' %>
	</div>
</div>

app/views/discoveries/index.html.erb
<div class="content">
	<div class="col-md-12">
		<h1 class="white-page-heading">Viewing All Discoveries in the </h1>
		<h1 class="red-page-heading">Parts Ninja Database</h1>
		<div class="header-border"></div>
	</div>
	<div class="col-md-8 col-md-offset-2">	
		<!-- <table class="table table-hover">
    		<thead>
    			<tr>
			        <th>Discovery Id</th>
			        <th>Submitted By</th>
			        <th>OEM Vehicle</th>
			        <th>Compatible Vehicle</th>
			        <th>Replaces</th>
			        <th>View</th>
              		<th>Delete</th>
		      	</tr>
    		</thead>
    		<tbody> -->
    			<div class="panel-group" id="accordion">
    			<%= render @discoveries %>
    		</div>
			<!-- </tbody>
  		</table> -->
	</div>
</div>

app/views/discoveries/new.html.erb
<div class="content">
	<div class="col-md-12">
		<h1 class="white-page-heading">So you discovered something</h1>
		<h1 class="red-page-heading">Create a Discovery</h1>
		<div class="header-border"></div>
	</div>
	<div class="col-md-10 col-md-offset-1">	
		<%= render 'form' %>
	</div>
</div>

app/views/discoveries/show.html.erb
<div class="content">
	<div class="col-md-12">
		<h1 class="white-page-heading">Viewing Discovery</h1>
		<h1 class="red-page-heading">Stuff</h1>
		<div class="header-border"></div>
	</div>
	<div class="row">
		<div class="col-md-9">
			<div class="ninja-panel pad-20">
				<div class="col-md-2 voting">	
						<h5>Rating</h5>
					<ul class="">
						<li class="grey-box"><%= link_to upvote_discovery_path(@discovery), method: :put do %><i class="fa fa-chevron-up fa-2x green"></i><% end %></li>
						<li><%= @discovery.score %></li>
						<li><%= link_to downvote_discovery_path(@discovery), method: :put do %><i class="fa fa-chevron-down fa-2x red"></i><% end %></li>
					</ul>
				</div>
				<div class="col-md-10">	
						<h5>This Part:</h5><p>
						<div class="col-md-4"><div class="form-header">Manufacturer:</div> <%= @discovery.part.manufacturer %><br><div class="form-header">Name:</div> <%= @discovery.part.name %><br><div class="form-header">Part Number:</div> <%= @discovery.part.part_number %><br></div>
						<div class="text-right"><%= link_to "View Part", @discovery.part, class: "btn btn-default btn-sm" %></div> 
				</div>
			</div>	
			<div class="ninja-panel pad-20 mrg-top-20">
				<h5>From this vehicle:</h5>
				<div class="col-md-4"><div class="form-header">Year:</div> <%= @discovery.oem.year %></div>
				<div class="col-md-4"><div class="form-header">Manufacturer:</div> <%= @discovery.oem.make %></div>
				<div class="col-md-4"><div class="form-header">Model:</div> <%= @discovery.oem.model %></div>
			</div>
			<div class="ninja-panel pad-20 mrg-top-20">
				<h5>Fits this vehicle:</h5>
				<div class="col-md-3"><div class="form-header">Part Number:</div> <%= @discovery.compatible.year %></div>
				<div class="col-md-3"><div class="form-header">Manufacturer:</div> <%= @discovery.compatible.make %></div>
				<div class="col-md-3"><div class="form-header">Description:</div> <%= @discovery.compatible.model %></div>
				<div class="col-md-3"><div class="form-header">What It Replaces</div> <%= @discovery.replaces %></div>
			</div>
			<div class="ninja-panel pad-20 mrg-top-20">
				<h5>Additional Information</h5>
				<div class="col-md-6"><div class="form-header">Comments:</div> <%= @discovery.comment %></div>
				<div class="col-md-6"><div class="form-header">Are Mods Required?</div> <%= @discovery.modifications %></div>
			</div>
			<% unless @steps.count == 0 %>
				<div class="ninja-panel pad-20 mrg-top-20">
					<div class="ninja-heading">Steps Required (<%= @steps.count %>)</div>
					<div class="header-border"></div>
					<%= render @steps %>
				</div>
			<% end %>
		</div>
		<div class="col-md-3">
			<div class="profile-sidebar ninja-panel">
				<div class="profile-userpic">
					<%= gravatar_for @discovery.user %>
				</div>
				<div class="profile-usertitle">
					<div class="profile-usertitle-name">
						<%= @discovery.user.username %>
					</div>
					<div class="profile-usertitle-job">
						Padawan
					</div>
					<div class="profile-discoveries">
						Discoveries: <%= @discovery.user.discoveries.count %>
					</div>
				</div>
				<div class="profile-userbuttons">
					<button type="button" class="btn btn-default btn-lg">Follow</button>
					<button type="button" class="btn btn-default btn-lg">Message</button>
				</div>
			</div>
		</div>
	</div>
</div>