config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  
  resources :parts do
    member do
      post :fitment
    end
  end

  resources :vehicles
  resources :discoveries do
    member do
      put "upvote" => "discoveries#upvote"
      put "downvote" => "discoveries#downvote"
    end
  end

  resources :users, only: [:show]

  get 'search' => 'search#index', as: :search
  get 'about' => 'pages#about'
  get 'blog' => 'pages#blog'
  get 'contact' => 'pages#contact'
  get 'help' => 'pages#help'

  root 'pages#home'

  

end

app/views/layouts/_content.html.erb
<div class="content">
	<div class="col-md-12">
		<h1 class="white-page-heading"><%= yield(:subheading) %></h1>
		<h1 class="red-page-heading"><%= yield(:heading) %></h1>
		<div class="header-border"></div>
	</div>
	<%= yield %>
</div>

app/views/layouts/_flash.html.erb
<!-- Can't click to close notices, alerts work fine though -->
<% if notice %>
	<div id="notice-wrapper">
		<p class="notice"><%= notice %><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></p>
	</div>
<% elsif alert %>
	<div id="notice-wrapper" >
		<p class="alert"><%= alert %><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></p>
	</div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Blog", blog_path %></li>
      <li><%= link_to "Help", help_path %></li>
    </ul>
    <ul class="social-icons">
      <li><%= link_to '<i class="fa fa-facebook fa-fw"></i>'.html_safe, 'https://facebook.com/thepartsninja', :target => "_blank" %></li>
      <li><%= link_to '<i class="fa fa-instagram fa-fw"></i>'.html_safe, 'https://facebook.com/thepartsninja', :target => "_blank" %></li>
      <li><%= link_to '<i class="fa fa-twitter fa-fw"></i>'.html_safe, 'https://facebook.com/thepartsninja', :target => "_blank" %></li>
    </ul>
  </footer>
</div>

app/views/layouts/_header.html.erb
<% if @search %>
<header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="intro-what">What are you</h2>
                        <h1 class="brand-heading">Looking for?</h1>
                        <%= render 'search/form' %>
                        <h4 class= "mrg-top-20 mrg-btm-5">Search the Compatibility Web: Millions of compatible parts right at your fingertips</h4>
                        <h2 class= "mrg-btm-5 red-heading"><%= @discoveries %> Discoveries Found, and counting...</h2>
                    </div>
                </div>
            </div>
        </div>
    </header>
<% else %>
<header class="intro header-positioning">
    
</header>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
          <i class="fa fa-bars"></i>
      </button>
        <%= link_to root_path, class:"navbar-brand" do %>
          <span class="light"><i class="fa fa-cogs"></i> Compatible</span>: The Parts Ninja
        <% end %>
    </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "Vehicles", vehicles_path %></li>
          <li><%= link_to "Parts", parts_path %></li>
          <li><%= link_to "Discoveries", discoveries_path %></li>
          <li><%= link_to "New Discovery", new_discovery_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Profile", current_user %></li>
              <li class="divider"></li>
              <li class="dropdown-header">Callin' it quits?</li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
	</head>
	<body data-target=".navbar-fixed-top">

		<%= render 'layouts/flash' %>
		<%= render 'layouts/navbar' %>
		<%= render 'layouts/header' %>
		<div class="container">
			<%= yield %>
		</div>
		<%= render 'layouts/footer' %>
		<div class="container">
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>